spring:
  application:
    name: nearsplit

  #jackson:
    # ===== í•„ìˆ˜ ì„¤ì • =====
    # ğŸ”µ REQUEST (ìš”ì²­): JSON â†’ DTO
    #mapper:
     # default-setter-info: skip  # null ê°’ì€ setter í˜¸ì¶œ ì•ˆ í•¨ â†’ ê¸°ì¡´ ê°’ ìœ ì§€   
      #  ã„´> ê·¼ë° ì‹ ê¸°í•˜ê²Œ.. yml íŒŒì¼ì—ì„œ ìš”ì²­ ì„¤ì •í•˜ëŠ” ê²Œ ì—†ì„ê¹Œ í–ˆëŠ”ë°.. ë©”ëª¨ ê°™ì€ê±°ì—ì„œ ë‚´ìš© ì‚¬ìš© í–ˆë‹¤ê°€ ê³µë°±ìœ¼ë¡œ ë°”ê¾¸ëŠ” ê²½ìš° ìˆ˜ì •ì´ ì•ˆë¨... ì´ëŸ° ì´ìŠˆ

    # ğŸŸ¢ RESPONSE (ì‘ë‹µ): DTO â†’ JSON
    #default-property-inclusion: non_null  # null í•„ë“œëŠ” JSONì— í¬í•¨ ì•ˆ í•¨

    # ===== ê¶Œì¥ ì„¤ì • (ì„ íƒ) =====
    #deserialization:
     # fail-on-unknown-properties: false  # ì•Œ ìˆ˜ ì—†ëŠ” í•„ë“œ ë¬´ì‹œ (API ë²„ì „ í˜¸í™˜ì„±)
    #serialization:
     # write-dates-as-timestamps: false  # LocalDateë¥¼ ISO-8601 í˜•ì‹ìœ¼ë¡œ ("2025-01-09")


  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true              # SQL Output(ì¶œë ¥)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true        # SQL Formating
        user_sql_comments: true # JPQL ì£¼ì„ í‘œì‹œ

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: nearsplit-consumer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: nearsplit-secret-key-change-this-in-production-must-be-at-least-256-bits
  expiration: 1800000 # 30ë¶„ #86400000  # 24 hours in milliseconds

logging:
  level:
    com.nearsplit: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: on_param

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
